/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/UY7mS502yix
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Fraunces } from 'next/font/google'

fraunces({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Navbar } from "./navbar";
import Image from "next/image";

export function LandingPage() {
  return (
    <div className="flex min-h-[100dvh] flex-col">
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
              <div className="flex flex-col justify-center space-y-4">
                <div className="space-y-2">
                  <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">
                    Earn Rewards by Staking Your Solana NFTs
                  </h1>
                  <p className="text-muted-foreground max-w-[600px] md:text-xl">
                    Our Solana NFT staking platform allows you to earn passive
                    income by staking your valuable NFTs. Enjoy the benefits of
                    decentralized finance while keeping your assets secure.
                  </p>
                </div>
                <div className="flex flex-col gap-2 min-[400px]:flex-row">
                  <Link
                    href="/stake"
                    className="focus-visible:ring-ring inline-flex h-10 items-center justify-center rounded-md bg-[#00FFA3] px-8 text-sm font-medium text-[#0D1117] shadow transition-colors hover:bg-[#00FFA3]/90 focus-visible:outline-none focus-visible:ring-1 disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    Start Staking
                  </Link>
                  <Link
                    href="https://discord.gg/bVShvrgsg8"
                    target="_blank"
                    className="border-input bg-background hover:bg-accent hover:text-accent-foreground focus-visible:ring-ring inline-flex h-10 items-center justify-center rounded-md border px-8 text-sm font-medium shadow-sm transition-colors focus-visible:outline-none focus-visible:ring-1 disabled:pointer-events-none disabled:opacity-50"
                  >
                    Learn More
                  </Link>
                </div>
              </div>
              <Image
                src="/nfts.webp"
                width="550"
                height="550"
                alt="Hero"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover sm:w-full lg:order-last lg:aspect-square"
              />
            </div>
          </div>
        </section>
        <section className="w-full bg-[#0D1117] py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-[#1F2937] px-3 py-1 text-sm text-[#00FFA3]">
                  Staking Process
                </div>
                <h2 className="text-3xl font-bold tracking-tighter text-white sm:text-5xl">
                  How It Works
                </h2>
                <p className="text-muted-foreground max-w-[900px] md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Our Solana NFT staking platform makes it easy to earn rewards.
                  Simply connect your wallet, select the NFTs you want to stake,
                  and start earning passive income.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-2 lg:gap-12">
              <Image
                src="/nfts-2.webp"
                width="550"
                height="310"
                alt="Staking Process"
                className="mx-auto rounded-xl object-center sm:w-full lg:order-last"
              />
              <div className="flex flex-col justify-center space-y-4">
                <ul className="grid gap-6">
                  <li>
                    <div className="grid gap-1">
                      <h3 className="text-xl font-bold text-white">
                        Connect Your Wallet
                      </h3>
                      <p className="text-muted-foreground">
                        Connect your Solana wallet to access your NFT
                        collection.
                      </p>
                    </div>
                  </li>
                  <li>
                    <div className="grid gap-1">
                      <h3 className="text-xl font-bold text-white">
                        Select NFTs to Stake
                      </h3>
                      <p className="text-muted-foreground">
                        Choose the NFTs you want to stake and start earning
                        rewards.
                      </p>
                    </div>
                  </li>
                  <li>
                    <div className="grid gap-1">
                      <h3 className="text-xl font-bold text-white">
                        Earn Passive Income
                      </h3>
                      <p className="text-muted-foreground">
                        Sit back and watch your rewards accumulate as your NFTs
                        generate income.
                      </p>
                    </div>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
